### ISSUE TITLE
Error at Passing Folder path with music files

### ISSUE THREAD

**Issue by dhakkann** [akashrchandran/syrics#24]
60%|███████████████████▏            | 87/145 [00:51<00:34,  1.68it/s]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/syrics", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/syrics/core.py", line 164, in main
    unable = fetch_files(link)
             ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/syrics/core.py", line 135, in fetch_files
    save_lyrics(format_lrc(lyrics_json), path=file_name)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/syrics/core.py", line 58, in format_lrc
    if (lyrics_json['lyrics']['syncType'] == 'UNSYNCED' and not config['force_synced']) or not config['synced_lyrics']:
                                                                ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'force_synced'
![IMG_20221102_162126](https://user-images.githubusercontent.com/98802609/199471635-2b9028a0-8fe1-49da-9d4b-a46f3a0240fd.jpg)

**Comment by akashrchandran** [comment]
Please try again, you will need to update the program.
```
pip install syrics --upgrade
```

**Comment by dhakkann** [comment]
Thanks
Works Well now
